import { useState } from 'react';
import { Code2, Brain, Zap, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function CodeQuizLanding() {
  const [hoveredCard, setHoveredCard] = useState(null);

  const languages = [
    {
      icon: "JS",
      name: "JavaScript",
      description: "Test your knowledge with 20 AI-generated questions on JavaScript.",
      color: "from-yellow-400 to-yellow-600"
    },
    {
      icon: "Py",
      name: "Python",
      description: "Test your knowledge with 20 AI-generated questions on Python.",
      color: "from-blue-400 to-blue-600"
    },
    {
      icon: "☕",
      name: "Java",
      description: "Test your knowledge with 20 AI-generated questions on Java.",
      color: "from-red-400 to-red-600"
    }
  ];

  const features = [
    {
      icon: <Brain className="w-8 h-8" />,
      title: "AI-Powered Questions",
      description: "Dynamic quiz questions generated by advanced AI to match your skill level."
    },
    {
      icon: <Zap className="w-8 h-8" />,
      title: "Instant Feedback",
      description: "Get immediate explanations for each answer to accelerate your learning."
    },
    {
      icon: <Trophy className="w-8 h-8" />,
      title: "Track Progress",
      description: "Monitor your improvement across multiple programming languages."
    }
  ];

  return (
    <div className="min-h-screen flex flex-col bg-gray-50">
      {/* Header */}
      <header className="bg-gray-800 text-white py-12 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <h1 className="text-2xl font-bold text-white">DevSphere</h1>
          <div className="flex items-center gap-4">
            <Link
              to="/login"
              className="px-6 py-2 rounded-lg font-medium text-white border border-purple-200 hover:bg-purple-700 hover:text-white hover:border-purple-700 transition"
            >
              Sign In
            </Link>
            <Link
              to="/register"
              className="px-6 py-2 rounded-lg font-medium text-white border border-purple-200 hover:bg-purple-700 hover:text-white hover:border-purple-700 transition"
            >
              Sign Up
            </Link>
          </div>
        </div>
      </header>
      {/* About Section */}
      <section className="bg-white py-20">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <h3 className="text-4xl font-bold text-gray-900 mb-4">About DevSphere</h3>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              DevSphere is an innovative learning platform that uses artificial intelligence to create personalized programming quizzes. Whether you're a beginner or an expert, our adaptive system helps you improve your coding skills efficiently.
            </p>
          </div>

          {/* Features Grid */}
          <div className="grid md:grid-cols-3 gap-8 mt-12">
            {features.map((feature, index) => (
              <div
                key={index}
                className="text-center p-8 rounded-2xl bg-gradient-to-br from-purple-50 to-white border border-purple-100 hover:border-purple-300 transition-all"
              >
                <div className="w-16 h-16 mx-auto mb-6 rounded-full bg-purple-600 text-white flex items-center justify-center">
                  {feature.icon}
                </div>
                <h4 className="text-xl font-bold text-gray-900 mb-3">{feature.title}</h4>
                <p className="text-gray-600 leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-12">
        <div className="max-w-7xl mx-auto px-6 text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Code2 className="w-6 h-6" />
            <span className="text-xl font-bold">DevSphere</span>
          </div>
          <p className="text-gray-400">Master programming languages with AI-powered quizzes</p>
          <p className="text-gray-500 mt-4 text-sm">© 2025 DevSphere. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}